// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UITreeNodePB2211.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from UITreeNodePB2211.proto</summary>
public static partial class UITreeNodePB2211Reflection {

  #region Descriptor
  /// <summary>File descriptor for UITreeNodePB2211.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static UITreeNodePB2211Reflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChZVSVRyZWVOb2RlUEIyMjExLnByb3RvIt0BChBVSVRyZWVOb2RlUEIyMjEx",
          "Eh8KF3B5dGhvbl9vYmplY3RfdHlwZV9uYW1lGAEgASgJEh0KFXB5dGhvbl9v",
          "YmplY3RfYWRkcmVzcxgEIAEoBhIjCghjaGlsZHJlbhgCIAMoCzIRLlVJVHJl",
          "ZU5vZGVQQjIyMTESLQoGZmllbGRzGAMgAygLMh0uVUlUcmVlTm9kZVBCMjIx",
          "MS5GaWVsZHNFbnRyeRo1CgtGaWVsZHNFbnRyeRILCgNrZXkYASABKAkSFQoF",
          "dmFsdWUYAiABKAsyBi5WYWx1ZToCOAEibAoFVmFsdWUSFQoLaW50MzJfdmFs",
          "dWUYASABKA9IABIWCgxkb3VibGVfdmFsdWUYAiABKAFIABIWCgxzdHJpbmdf",
          "dmFsdWUYAyABKAxIABIUCgpib29sX3ZhbHVlGAQgASgISABCBgoEa2luZEIC",
          "SANiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::UITreeNodePB2211), global::UITreeNodePB2211.Parser, new[]{ "PythonObjectTypeName", "PythonObjectAddress", "Children", "Fields" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
          new pbr::GeneratedClrTypeInfo(typeof(global::Value), global::Value.Parser, new[]{ "Int32Value", "DoubleValue", "StringValue", "BoolValue" }, new[]{ "Kind" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class UITreeNodePB2211 : pb::IMessage<UITreeNodePB2211>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<UITreeNodePB2211> _parser = new pb::MessageParser<UITreeNodePB2211>(() => new UITreeNodePB2211());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<UITreeNodePB2211> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::UITreeNodePB2211Reflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UITreeNodePB2211() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UITreeNodePB2211(UITreeNodePB2211 other) : this() {
    pythonObjectTypeName_ = other.pythonObjectTypeName_;
    pythonObjectAddress_ = other.pythonObjectAddress_;
    children_ = other.children_.Clone();
    fields_ = other.fields_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UITreeNodePB2211 Clone() {
    return new UITreeNodePB2211(this);
  }

  /// <summary>Field number for the "python_object_type_name" field.</summary>
  public const int PythonObjectTypeNameFieldNumber = 1;
  private string pythonObjectTypeName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string PythonObjectTypeName {
    get { return pythonObjectTypeName_; }
    set {
      pythonObjectTypeName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "python_object_address" field.</summary>
  public const int PythonObjectAddressFieldNumber = 4;
  private ulong pythonObjectAddress_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong PythonObjectAddress {
    get { return pythonObjectAddress_; }
    set {
      pythonObjectAddress_ = value;
    }
  }

  /// <summary>Field number for the "children" field.</summary>
  public const int ChildrenFieldNumber = 2;
  private static readonly pb::FieldCodec<global::UITreeNodePB2211> _repeated_children_codec
      = pb::FieldCodec.ForMessage(18, global::UITreeNodePB2211.Parser);
  private readonly pbc::RepeatedField<global::UITreeNodePB2211> children_ = new pbc::RepeatedField<global::UITreeNodePB2211>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::UITreeNodePB2211> Children {
    get { return children_; }
  }

  /// <summary>Field number for the "fields" field.</summary>
  public const int FieldsFieldNumber = 3;
  private static readonly pbc::MapField<string, global::Value>.Codec _map_fields_codec
      = new pbc::MapField<string, global::Value>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::Value.Parser), 26);
  private readonly pbc::MapField<string, global::Value> fields_ = new pbc::MapField<string, global::Value>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::MapField<string, global::Value> Fields {
    get { return fields_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as UITreeNodePB2211);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(UITreeNodePB2211 other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (PythonObjectTypeName != other.PythonObjectTypeName) return false;
    if (PythonObjectAddress != other.PythonObjectAddress) return false;
    if(!children_.Equals(other.children_)) return false;
    if (!Fields.Equals(other.Fields)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (PythonObjectTypeName.Length != 0) hash ^= PythonObjectTypeName.GetHashCode();
    if (PythonObjectAddress != 0UL) hash ^= PythonObjectAddress.GetHashCode();
    hash ^= children_.GetHashCode();
    hash ^= Fields.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (PythonObjectTypeName.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(PythonObjectTypeName);
    }
    children_.WriteTo(output, _repeated_children_codec);
    fields_.WriteTo(output, _map_fields_codec);
    if (PythonObjectAddress != 0UL) {
      output.WriteRawTag(33);
      output.WriteFixed64(PythonObjectAddress);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (PythonObjectTypeName.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(PythonObjectTypeName);
    }
    children_.WriteTo(ref output, _repeated_children_codec);
    fields_.WriteTo(ref output, _map_fields_codec);
    if (PythonObjectAddress != 0UL) {
      output.WriteRawTag(33);
      output.WriteFixed64(PythonObjectAddress);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (PythonObjectTypeName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(PythonObjectTypeName);
    }
    if (PythonObjectAddress != 0UL) {
      size += 1 + 8;
    }
    size += children_.CalculateSize(_repeated_children_codec);
    size += fields_.CalculateSize(_map_fields_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(UITreeNodePB2211 other) {
    if (other == null) {
      return;
    }
    if (other.PythonObjectTypeName.Length != 0) {
      PythonObjectTypeName = other.PythonObjectTypeName;
    }
    if (other.PythonObjectAddress != 0UL) {
      PythonObjectAddress = other.PythonObjectAddress;
    }
    children_.Add(other.children_);
    fields_.Add(other.fields_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          PythonObjectTypeName = input.ReadString();
          break;
        }
        case 18: {
          children_.AddEntriesFrom(input, _repeated_children_codec);
          break;
        }
        case 26: {
          fields_.AddEntriesFrom(input, _map_fields_codec);
          break;
        }
        case 33: {
          PythonObjectAddress = input.ReadFixed64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          PythonObjectTypeName = input.ReadString();
          break;
        }
        case 18: {
          children_.AddEntriesFrom(ref input, _repeated_children_codec);
          break;
        }
        case 26: {
          fields_.AddEntriesFrom(ref input, _map_fields_codec);
          break;
        }
        case 33: {
          PythonObjectAddress = input.ReadFixed64();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class Value : pb::IMessage<Value>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Value> _parser = new pb::MessageParser<Value>(() => new Value());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Value> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::UITreeNodePB2211Reflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Value() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Value(Value other) : this() {
    switch (other.KindCase) {
      case KindOneofCase.Int32Value:
        Int32Value = other.Int32Value;
        break;
      case KindOneofCase.DoubleValue:
        DoubleValue = other.DoubleValue;
        break;
      case KindOneofCase.StringValue:
        StringValue = other.StringValue;
        break;
      case KindOneofCase.BoolValue:
        BoolValue = other.BoolValue;
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Value Clone() {
    return new Value(this);
  }

  /// <summary>Field number for the "int32_value" field.</summary>
  public const int Int32ValueFieldNumber = 1;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Int32Value {
    get { return kindCase_ == KindOneofCase.Int32Value ? (int) kind_ : 0; }
    set {
      kind_ = value;
      kindCase_ = KindOneofCase.Int32Value;
    }
  }

  /// <summary>Field number for the "double_value" field.</summary>
  public const int DoubleValueFieldNumber = 2;
  /// <summary>
  /// Represents a double value.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double DoubleValue {
    get { return kindCase_ == KindOneofCase.DoubleValue ? (double) kind_ : 0D; }
    set {
      kind_ = value;
      kindCase_ = KindOneofCase.DoubleValue;
    }
  }

  /// <summary>Field number for the "string_value" field.</summary>
  public const int StringValueFieldNumber = 3;
  /// <summary>
  /// Represents a string value.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString StringValue {
    get { return kindCase_ == KindOneofCase.StringValue ? (pb::ByteString) kind_ : pb::ByteString.Empty; }
    set {
      kind_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      kindCase_ = KindOneofCase.StringValue;
    }
  }

  /// <summary>Field number for the "bool_value" field.</summary>
  public const int BoolValueFieldNumber = 4;
  /// <summary>
  /// Represents a boolean value.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool BoolValue {
    get { return kindCase_ == KindOneofCase.BoolValue ? (bool) kind_ : false; }
    set {
      kind_ = value;
      kindCase_ = KindOneofCase.BoolValue;
    }
  }

  private object kind_;
  /// <summary>Enum of possible cases for the "kind" oneof.</summary>
  public enum KindOneofCase {
    None = 0,
    Int32Value = 1,
    DoubleValue = 2,
    StringValue = 3,
    BoolValue = 4,
  }
  private KindOneofCase kindCase_ = KindOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public KindOneofCase KindCase {
    get { return kindCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearKind() {
    kindCase_ = KindOneofCase.None;
    kind_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Value);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Value other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Int32Value != other.Int32Value) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(DoubleValue, other.DoubleValue)) return false;
    if (StringValue != other.StringValue) return false;
    if (BoolValue != other.BoolValue) return false;
    if (KindCase != other.KindCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (kindCase_ == KindOneofCase.Int32Value) hash ^= Int32Value.GetHashCode();
    if (kindCase_ == KindOneofCase.DoubleValue) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(DoubleValue);
    if (kindCase_ == KindOneofCase.StringValue) hash ^= StringValue.GetHashCode();
    if (kindCase_ == KindOneofCase.BoolValue) hash ^= BoolValue.GetHashCode();
    hash ^= (int) kindCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (kindCase_ == KindOneofCase.Int32Value) {
      output.WriteRawTag(13);
      output.WriteSFixed32(Int32Value);
    }
    if (kindCase_ == KindOneofCase.DoubleValue) {
      output.WriteRawTag(17);
      output.WriteDouble(DoubleValue);
    }
    if (kindCase_ == KindOneofCase.StringValue) {
      output.WriteRawTag(26);
      output.WriteBytes(StringValue);
    }
    if (kindCase_ == KindOneofCase.BoolValue) {
      output.WriteRawTag(32);
      output.WriteBool(BoolValue);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (kindCase_ == KindOneofCase.Int32Value) {
      output.WriteRawTag(13);
      output.WriteSFixed32(Int32Value);
    }
    if (kindCase_ == KindOneofCase.DoubleValue) {
      output.WriteRawTag(17);
      output.WriteDouble(DoubleValue);
    }
    if (kindCase_ == KindOneofCase.StringValue) {
      output.WriteRawTag(26);
      output.WriteBytes(StringValue);
    }
    if (kindCase_ == KindOneofCase.BoolValue) {
      output.WriteRawTag(32);
      output.WriteBool(BoolValue);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (kindCase_ == KindOneofCase.Int32Value) {
      size += 1 + 4;
    }
    if (kindCase_ == KindOneofCase.DoubleValue) {
      size += 1 + 8;
    }
    if (kindCase_ == KindOneofCase.StringValue) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(StringValue);
    }
    if (kindCase_ == KindOneofCase.BoolValue) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Value other) {
    if (other == null) {
      return;
    }
    switch (other.KindCase) {
      case KindOneofCase.Int32Value:
        Int32Value = other.Int32Value;
        break;
      case KindOneofCase.DoubleValue:
        DoubleValue = other.DoubleValue;
        break;
      case KindOneofCase.StringValue:
        StringValue = other.StringValue;
        break;
      case KindOneofCase.BoolValue:
        BoolValue = other.BoolValue;
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 13: {
          Int32Value = input.ReadSFixed32();
          break;
        }
        case 17: {
          DoubleValue = input.ReadDouble();
          break;
        }
        case 26: {
          StringValue = input.ReadBytes();
          break;
        }
        case 32: {
          BoolValue = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 13: {
          Int32Value = input.ReadSFixed32();
          break;
        }
        case 17: {
          DoubleValue = input.ReadDouble();
          break;
        }
        case 26: {
          StringValue = input.ReadBytes();
          break;
        }
        case 32: {
          BoolValue = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
